import { indexCardSet } from "@/types/indexCard";

export const DummyBreadSetList: indexCardSet[] = [
  {
    cardSetId: 1,
    title: "정보처리기사 1회차",
    isLike: true,
    correctCardCnt: 15,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "운영체제", "네트워크", "데이터베이스"],
  },
  {
    cardSetId: 2,
    title: "정보처리기사 2회차",
    isLike: false,
    correctCardCnt: 10,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "네트워크", "데이터베이스"],
  },
  {
    cardSetId: 3,
    title: "정보처리기사 3회차",
    isLike: true,
    correctCardCnt: 18,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "데이터베이스", "시스템일반"],
  },
  {
    cardSetId: 4,
    title: "정보처리기사 4회차",
    isLike: false,
    correctCardCnt: 5,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "시스템일반"],
  },
  {
    cardSetId: 5,
    title: "정보처리기사 5회차",
    isLike: true,
    correctCardCnt: 12,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "보안"],
  },
  {
    cardSetId: 6,
    title: "정보처리기사 6회차",
    isLike: false,
    correctCardCnt: 7,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "운영체제", "시스템일반"],
  },
  {
    cardSetId: 7,
    title: "정보처리기사 7회차",
    isLike: true,
    correctCardCnt: 20,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "네트워크"],
  },
  {
    cardSetId: 8,
    title: "정보처리기사 8회차",
    isLike: false,
    correctCardCnt: 3,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "데이터베이스"],
  },
  {
    cardSetId: 9,
    title: "정보처리기사 9회차",
    isLike: false,
    correctCardCnt: 17,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "시스템일반"],
  },
  {
    cardSetId: 10,
    title: "정보처리기사 10회차",
    isLike: true,
    correctCardCnt: 11,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "보안"],
  },
  {
    cardSetId: 11,
    title: "정보처리기사 11회차",
    isLike: false,
    correctCardCnt: 13,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "운영체제"],
  },
  {
    cardSetId: 12,
    title: "정보처리기사 12회차",
    isLike: true,
    correctCardCnt: 16,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "네트워크"],
  },
  {
    cardSetId: 13,
    title: "정보처리기사 13회차",
    isLike: false,
    correctCardCnt: 9,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "데이터베이스"],
  },
  {
    cardSetId: 14,
    title: "정보처리기사 14회차",
    isLike: true,
    correctCardCnt: 8,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "시스템일반"],
  },
  {
    cardSetId: 15,
    title: "정보처리기사 15회차",
    isLike: false,
    correctCardCnt: 14,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "보안"],
  },
  {
    cardSetId: 16,
    title: "정보처리기사 16회차",
    isLike: true,
    correctCardCnt: 6,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "운영체제"],
  },
  {
    cardSetId: 17,
    title: "정보처리기사 17회차",
    isLike: false,
    correctCardCnt: 19,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "네트워크"],
  },
  {
    cardSetId: 18,
    title: "정보처리기사 18회차",
    isLike: true,
    correctCardCnt: 2,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "데이터베이스"],
  },
  {
    cardSetId: 19,
    title: "정보처리기사 19회차",
    isLike: false,
    correctCardCnt: 0,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "시스템일반"],
  },
  {
    cardSetId: 20,
    title: "정보처리기사 20회차",
    isLike: true,
    correctCardCnt: 20,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "보안"],
  },
  {
    cardSetId: 21,
    title: "정보처리기사 21회차",
    isLike: true,
    correctCardCnt: 4,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "운영체제"],
  },
  {
    cardSetId: 22,
    title: "정보처리기사 22회차",
    isLike: false,
    correctCardCnt: 11,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "네트워크"],
  },
  {
    cardSetId: 23,
    title: "정보처리기사 23회차",
    isLike: true,
    correctCardCnt: 13,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "데이터베이스"],
  },
  {
    cardSetId: 24,
    title: "정보처리기사 24회차",
    isLike: false,
    correctCardCnt: 1,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "시스템일반"],
  },
  {
    cardSetId: 25,
    title: "정보처리기사 25회차",
    isLike: true,
    correctCardCnt: 12,
    totalCardCnt: 20,
    hashTags: ["정보처리기사", "보안"],
  },
];
